language: generic

services:
  - docker

before_install:
  - docker build -t alan-turing-institute/csvwrangling .

script:
  - mkdir -p /home/travis/build/alan-turing-institute/results
  - docker run -v /home/travis/build/alan-turing-institute/results:/CSV_Wrangling/test alan-turing-institute/csvwrangling /bin/bash -c "make output && git diff"
